services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bookdb
    networks:
      - backend

  config-server:
    build: ./config_server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config_repo:/config_repo
    networks:
      - backend

  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend
    depends_on:
      - mysql

  book-service:
    build: ./services/book_service
    container_name: book-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    restart: on-failure
    networks:
      - backend
      

#  book-service-1:
#    build: ./services/book_service
#    container_name: book-service-1
#    ports:
#      - "8082:8081"
#    environment:
#      SPRING_PROFILES_ACTIVE: instance1
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookdb
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: admin
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#    networks:
#      - backend
#    depends_on:
#      - mysql
#      - eureka-server

#  book-service-2:
#    build: ./services/book_service
#    container_name: book-service-2
#    ports:
#      - "8083:8081" 
#    environment:
#      SPRING_PROFILES_ACTIVE: instance2
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bookdb
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: admin
#      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
#    networks:
#      - backend
#    depends_on:
#      - mysql
#      - eureka-server      

networks:
  backend:
