version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bookdb
    networks:
      - backend

  config-server:
    build: ./config_server
    container_name: config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config_repo:/config_repo
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend
    depends_on:
      - mysql

  book-service:
    build: ./services/book_service
    container_name: book-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    restart: on-failure
    networks:
      - backend

  membership-service:
    build: ./services/membership_service
    container_name: membership-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    restart: on-failure
    networks:
      - backend

  forum-service:
    build: ./services/forum_service
    container_name: forum-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - eureka-server
      - config-server
    restart: on-failure
    networks:
      - backend

networks:
  backend:
