server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/bookdb
    username: root
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
